### ISSUE TITLE
建议 nuget & doc 来一套

### ISSUE THREAD

**Issue by taadis** [liningit/LnskyDB#1]
RT...
- nuget 发一个,  方便大家下载安装和使用
- doc 文档来一套, 方便新手和老鸟来看看

**Comment by liningit** [comment]
好主意,nuget我抽空给加上,doc 文档在README.md里面已经写了

**Comment by taadis** [comment]
文档太少了...老项目老鸟基本不会换这么基础的库...那么突破的市场大部分是新人/新手/尝鲜/新项目...那么文档从浅到深, 各个角度和实例的尽可能多补充点...才有利于 LnskyDB 的发展...

**Comment by liningit** [comment]
> 文档太少了...老项目老鸟基本不会换这么基础的库...那么突破的市场大部分是新人/新手/尝鲜/新项目...那么文档从浅到深, 各个角度和实例的尽可能多补充点...才有利于 LnskyDB 的发展...

非常感谢你的建议,我后面会慢慢完善doc

**Comment by liningit** [comment]
> 文档太少了...老项目老鸟基本不会换这么基础的库...那么突破的市场大部分是新人/新手/尝鲜/新项目...那么文档从浅到深, 各个角度和实例的尽可能多补充点...才有利于 LnskyDB 的发展...

Nuget地址已经加上了
https://www.nuget.org/packages/LnskyDB/

**Comment by liningit** [comment]
文档我会慢慢完善的

**Comment by taadis** [comment]
可以的 大拇哥

**Comment by jianxuanbing** [comment]
建议写些多表查询的例子，单表的都很容易搞

**Comment by liningit** [comment]
> 建议写些多表查询的例子，单表的都很容易搞

多表查询建议手写sql.或者直接用EF,另外不太推荐连表查询,这样以后不好分库

**Comment by liningit** [comment]
> 可以的 大拇哥

https://liningit.github.io/LnskyDB/
这是文档地址后面会慢慢完善文档

**Comment by taadis** [comment]
@liningit 积极发电...可以的

**Comment by taadis** [comment]
@liningit docsify 实现的文档么? 看着套路很像

**Comment by liningit** [comment]
> @liningit docsify 实现的文档么? 看着套路很像

是的,还是现学的.以前没搞过

**Comment by liningit** [comment]
> 建议写些多表查询的例子，单表的都很容易搞

最新版本已经支持多表查询了
文档地址:
https://liningit.github.io/LnskyDB/#/join
