### ISSUE TITLE
分库分表

### ISSUE THREAD

**Issue by zgmqdl** [liningit/LnskyDB#6]
分库分表的规则在哪里设定

**Comment by liningit** [comment]
在实例类里面的,
public override ShuffledModel GetShuffledModel()
        {
            if (DBModel_ShuffledTempDate == DateTime.MinValue)
            {
                throw new NoShuffledException(GetDBModel_TableName(), "分库分表时间,ShuffledTempDate");
            }
            return ShuffledByDbTable(DBModel_ShuffledTempDate);
        }

**Comment by liningit** [comment]
这儿可以自定义一个ShuffledByDbTable实现按你的要求分库分表,默认是按年分库按月分表

**Comment by zgmqdl** [comment]
您好，这个分库分表的规则是提前设定好的是吧，可以动态修改吗？比如当我数据库里面某个字段为true的时候让分表，每周分一次库是否可以实现？

**Comment by liningit** [comment]
> 您好，这个分库分表的规则是提前设定好的是吧，可以动态修改吗？比如当我数据库里面某个字段为true的时候让分表，每周分一次库是否可以实现？

你自己实现一个ShuffledModel里面按你的需求进行分库分表就可以了

**Comment by liningit** [comment]
> 您好，这个分库分表的规则是提前设定好的是吧，可以动态修改吗？比如当我数据库里面某个字段为true的时候让分表，每周分一次库是否可以实现？
你根据自己的需求返回一个ShuffledModel就可以了,ShuffledModel中包含两个属性 一个是DBId是库的用来分库用的,如果不分库设置为空就可以了,还有一个是TableId是用来分表用的,如果不分表就设置为空就可以了

**Comment by liningit** [comment]
> 您好，这个分库分表的规则是提前设定好的是吧，可以动态修改吗？比如当我数据库里面某个字段为true的时候让分表，每周分一次库是否可以实现？
下面这代码就是按年分库,按周分表的
   public override ShuffledModel GetShuffledModel()
        {
            if (DBModel_ShuffledTempDate == DateTime.MinValue)
            {
                throw new NoShuffledException(GetDBModel_TableName(), "分库分表时间,ShuffledTempDate");
            }
            return new ShuffledModel(DBModel_ShuffledTempDate.Year.ToString(), new GregorianCalendar().GetWeekOfYear(DateTime.Now, CalendarWeekRule.FirstDay, DayOfWeek.Monday).ToString())
        }

**Comment by zgmqdl** [comment]
您好，我刚试了一下，是不是得提前新建好数据库才行，不支持程序自己去创建数据库，我用是MSSQL2014

**Comment by liningit** [comment]
> 您好，我刚试了一下，是不是得提前新建好数据库才行，不支持程序自己去创建数据库，我用是MSSQL2014

没错数据库和表要自己创建

**Comment by zgmqdl** [comment]
[Route("[controller]/[action]")]
    [ApiController]
    public class ProductSaleByDayController : ControllerBase
    {
        static int i = 0;
        private static IRepository<ProductSaleByDayEntity> GetRepository()
        {
            i++;
            if (i % 2 == 0)
            {
                //可以通过工厂创建
                return RepositoryFactory.Create<ProductSaleByDayEntity>();
            }
            else
            {
                //也可以继承实例化
                return new ProductSaleByDayRepository();
            }
        }
这段代码为什么要定义一个变量i呢

**Comment by liningit** [comment]
这儿只是为了表现可以通过两种方式创建仓储,你实际使用中只要根据自己的情况选择一种方式就可以了

**Comment by liningit** [comment]
> [Route("[controller]/[action]")]
> [ApiController]
> public class ProductSaleByDayController : ControllerBase
> {
> static int i = 0;
> private static IRepository GetRepository()
> {
> i++;
> if (i % 2 == 0)
> {
> //可以通过工厂创建
> return RepositoryFactory.Create();
> }
> else
> {
> //也可以继承实例化
> return new ProductSaleByDayRepository();
> }
> }
> 这段代码为什么要定义一个变量i呢

这儿只是为了表现可以通过两种方式创建仓储,你实际使用中只要根据自己的情况选择一种方式就可以了

**Comment by zgmqdl** [comment]
如果查询指定的列应该用哪个方法

**Comment by liningit** [comment]
> 如果查询指定的列应该用哪个方法

  query.Select(m => m.SysNo);

**Comment by zgmqdl** [comment]
var query = QueryFactory.Create<tStatus>();
            query.Select(m=>m.FJTID);
            var rep = RepositoryFactory.Create<tStatus>();
              result.data= rep.GetList(query);
仿佛不行，我这样写了查询返回的仍然是全部字段的数据

**Comment by liningit** [comment]
var query = QueryFactory.Create();
var q2=query.Select(m=>m.FJTID);
var rep = RepositoryFactory.Create();
result.data= rep.GetList(q2);

**Comment by liningit** [comment]
> var query = QueryFactory.Create();
> query.Select(m=>m.FJTID);
> var rep = RepositoryFactory.Create();
> result.data= rep.GetList(query);
> 仿佛不行，我这样写了查询返回的仍然是全部字段的数据

应该这样写:
var query = QueryFactory.Create();
var q2=query.Select(m=>m.FJTID);
var rep = RepositoryFactory.Create();
result.data= rep.GetList(q2);

**Comment by zgmqdl** [comment]
对，我试了一下，这样写可以的。但是分库分表的时候需要加上时间以后，就不能这样写了，不知道是否是这样，这个可以支持一下吗，或者在哪里可以修改一下

**Comment by liningit** [comment]
> 对，我试了一下，这样写可以的。但是分库分表的时候需要加上时间以后，就不能这样写了，不知道是否是这样，这个可以支持一下吗，或者在哪里可以修改一下

分库分表一样可以这样写的只是要多加一句话指定是哪个库
var query = QueryFactory.Create();
 query.DBModel.DBModel_ShuffledTempDate = new DateTime(2019, 01, 01);//这儿表示查19年1月的库和表
var q2=query.Select(m=>m.FJTID);
var rep = RepositoryFactory.Create();
result.data= rep.GetList(q2);

**Comment by zgmqdl** [comment]
是的，但这个只能查询一个库，如果我想查询多个库的话貌似不支持的。
var q2=query.Select(m=>m.FJTID);
var rep = RepositoryFactory.Create();
result.data= rep.GetList(q2,stTime,endTime);
最好能给GetList和GetPag再增加一种实现(ISelectResukt<R>,stTime,endTime)

**Comment by liningit** [comment]
这个方法需要你自己写代码来实现,因为每个实体使用的分库分表规则并不相同.
比如你的分库分表规则是按周分表
而我的是按月分表,所以之歌方法只能自己实现.你可以定义一个仓储实现Repository<T>
