### ISSUE TITLE
ProductSaleByDayController中GetPaging接口和GetList接口有错误

### ISSUE THREAD

**Issue by zgmqdl** [liningit/LnskyDB#7]
An unhandled exception occurred while processing the request.
SqlException: 'OFFSET' 附近有语法错误。
在 FETCH 语句中选项 NEXT 的用法无效。
System.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)

**Comment by liningit** [comment]
> NEXT

你的sql版本是不是2012以前的版本?OFFSET'要sql2012以后才可以支持
